name: 'Setup Snyk Variables'
description: 'Reads config.json and sets up Snyk-related variables and tags as outputs.'
outputs:
  proj_criticality:
    description: "Project business criticality"
    value: ${{ steps.set_vars.outputs.proj_criticality }}
  proj_env:
    description: "Project environment"
    value: ${{ steps.set_vars.outputs.proj_env }}
  proj_lifecycle:
    description: "Project lifecycle"
    value: ${{ steps.set_vars.outputs.proj_lifecycle }}
  proj_reponame:
    description: "Repository name"
    value: ${{ steps.set_vars.outputs.proj_reponame }}
  proj_repoorg:
    description: "Repository organization"
    value: ${{ steps.set_vars.outputs.proj_repoorg }}
  snyk_scm_integration_id:
    description: "Snyk SCM Integration ID"
    value: ${{ steps.set_vars.outputs.snyk_scm_integration_id }}
  snyk_org_id:
    description: "Snyk Organization ID"
    value: ${{ steps.set_vars.outputs.snyk_org_id }}
  snyk_tags:
    description: "Comma-separated Snyk tags"
    value: ${{ steps.set_vars.outputs.snyk_tags }}

runs:
  using: "composite"
  steps:
    - name: Set Project Environment Variables
      id: set_vars
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        REPO_ORG=$(echo "${{ github.repository }}" | cut -d'/' -f1)

        # Read all values from config.json
        CONFIG_FILE=".github/config.json"
        SNYK_INTEGRATION_ID=$(jq -r '.snykScmIntegration' $CONFIG_FILE)
        SNYK_ORG_ID=$(jq -r '.snykOrg' $CONFIG_FILE)
        ENV=$(jq -r '.snykproject_attributes.env' $CONFIG_FILE)
        LIFECYCLE=$(jq -r '.snykproject_attributes.lifecycle' $CONFIG_FILE)
        CRITICALITY=$(jq -r '.snykproject_attributes.businesscriticality' $CONFIG_FILE)

        DATA_SENSITIVITY=$(jq -r '.snyktags.security_and_compliance.data_sensitivity' .github/config.json)
        COMPLIANCE_FRAMEWORK=$(jq -r '.snyktags.security_and_compliance.compliance_framework' .github/config.json)
        CONTAINS_PII=$(jq -r '.snyktags.security_and_compliance.contains_pii' .github/config.json)
        SECURITY_TIER=$(jq -r '.snyktags.security_and_compliance.security_tier' .github/config.json)
        REQUIRES_ACTION_SCANNING=$(jq -r '.snyktags.security_and_compliance.requires_action_scanning' .github/config.json)
        REQUIRES_MULTI_PARTY_REVIEW=$(jq -r '.snyktags.security_and_compliance.requires_multi_party_review' .github/config.json)

        APP_NAME=$(jq -r '.snyktags.project_and_team_management.project_name' .github/config.json)
        TEAMS=$(jq -r '.snyktags.project_and_team_management.teams' .github/config.json)
        PROJECT_STATUS=$(jq -r '.snyktags.project_and_team_management.project_status' .github/config.json)
        COST_CENTER=$(jq -r '.snyktags.project_and_team_management.cost_center' .github/config.json)
        BUSINESS_UNIT=$(jq -r '.snyktags.project_and_team_management.business_unit' .github/config.json)
        REVIEW_CYCLE=$(jq -r '.snyktags.project_and_team_management.review_cycle' .github/config.json)

        ENVIRONMENT=$(jq -r '.snyktags.operations_and_infrastructure.environment' .github/config.json)
        SERVICE_NAME=$(jq -r '.snyktags.operations_and_infrastructure.service_name' .github/config.json)
        RUNTIME_ENVIRONMENT=$(jq -r '.snyktags.operations_and_infrastructure.runtime_environment' .github/config.json)
        OPS_TIER=$(jq -r '.snyktags.operations_and_infrastructure.ops_tier' .github/config.json)
        DEPLOYMENT_TYPE=$(jq -r '.snyktags.operations_and_infrastructure.deployment_type' .github/config.json)

        REPOSITORY_TYPE=$(jq -r '.snyktags.general_and_informational.repository_type' .github/config.json)
        CONTACTS=$(jq -r '.snyktags.general_and_informational.contacts' .github/config.json)

        echo "Deploying ${APP_NAME} to the ${ENV} environment."
        echo "The target AWS region is: ${AWS_REGION}"

        # prepare the Snyk tags
        SNYK_TAGS="data_sensitivity=${DATA_SENSITIVITY}"
        SNYK_TAGS="${SNYK_TAGS},compliance_framework=${COMPLIANCE_FRAMEWORK},contains_pii=${CONTAINS_PII}"
        SNYK_TAGS="${SNYK_TAGS},security_tier=${SECURITY_TIER},requires_action_scanning=${REQUIRES_ACTION_SCANNING}"
        SNYK_TAGS="${SNYK_TAGS},requires_multi_party_review=${REQUIRES_MULTI_PARTY_REVIEW},project_name=${APP_NAME}"
        SNYK_TAGS="${SNYK_TAGS},teams=${TEAMS},project_status=${PROJECT_STATUS},cost_center=${COST_CENTER}"
        SNYK_TAGS="${SNYK_TAGS},business_unit=${BUSINESS_UNIT},review_cycle=${REVIEW_CYCLE},environment=${ENVIRONMENT}"
        SNYK_TAGS="${SNYK_TAGS},service_name=${SERVICE_NAME},runtime_environment=${RUNTIME_ENVIRONMENT}"
        SNYK_TAGS="${SNYK_TAGS},ops_tier=${OPS_TIER},deployment_type=${DEPLOYMENT_TYPE}"
        SNYK_TAGS="${SNYK_TAGS},repository_type=${REPOSITORY_TYPE},contacts=${CONTACTS}"
        SNYK_TAGS="${SNYK_TAGS%,}"

        echo "proj_criticality=$CRITICALITY" >> $GITHUB_OUTPUT
        echo "proj_env=$ENV" >> $GITHUB_OUTPUT
        echo "proj_lifecycle=$LIFECYCLE" >> $GITHUB_OUTPUT
        echo "proj_reponame=$REPO_NAME" >> $GITHUB_OUTPUT
        echo "proj_repoorg=$REPO_ORG" >> $GITHUB_OUTPUT
        echo "snyk_scm_integration_id=${SNYK_INTEGRATION_ID}" >> $GITHUB_OUTPUT
        echo "snyk_org_id=${SNYK_ORG_ID}" >> $GITHUB_OUTPUT
        echo "snyk_tags=${SNYK_TAGS}" >> $GITHUB_OUTPUT
      shell: bash